### PR TITLE
Remove humantime

### PR DESCRIPTION
**Pull request by Salanoid**
Fix for: Remove unnecessary dependency #781

### CODE REVIEW

**Comment by sophie-cluml** [comment]
Hello Salanoid, thank you for your interest and contribution in this project. In the current codebase, humantime-serde is directly used, so I think we can remove humantime, but keep humantime-serde.

**Comment by Salanoid** [comment]
Thank you for the reply, I have added the humantime-serde back.

**Comment by sophie-cluml** [comment]
Could you check the failing "CI / check"? I think it can be resolved by updating Cargo.lock file, which I believe can be achieved by `cargo check` or `cargo build`.

**Comment by sophie-cluml** [comment]
It seems like `cargo update` was ran, and it caused update of dependency crates overall. Since we would like to focus on removing humantime for this issue, could you limit the scope of change to humantime?

**Review by sophie-cluml — APPROVED** [review]

**Pull request merged**
