### PR TITLE
Rename the public methods related to certificates

### LINKED ISSUE #800: Fix misleading log in certificate_info - refactoring
아래의 코드로 변경 작업

```
pub fn subject_from_cert(cert_info: &[CertificateDer]) -> Result<(String, String)> {
    subject_from_cert_opt(cert_info, false)
}

pub fn subject_from_cert_verbose(cert_info: &[CertificateDer]) -> Result<(String, String)> {
    subject_from_cert_opt(cert_info, true)
}

fn subject_from_cert_opt(cert_info: &[CertificateDer], logging: bool) -> Result<(String, String)> {
     ...
}
```

https://github.com/aicers/giganto/pull/792#discussion_r1719122340

### PR DESCRIPTION
**Pull request by henry0715-dev**
### Desc

modify function
certificate_info_default -> subject_from_cert_opt
subject_from_cert, subject_from_cert_verbose

### Refenece

Close #800

### CODE REVIEW

**Comment by sehkone** [comment]
I suggest the following commit message:

"Rename the public methods related to certificates"

**Comment by sophie-cluml** [comment]
Could you add something like "close" before #800 in the description, so that successfully merging this pull request may close that issue.

**Review by sophie-cluml — APPROVED** [review]
LGTM

**Comment by sehkone** [comment]
@henry0715-dev @sophie-cluml 

Even though this has been merged, I can't help but mention that the body of this commit message should have been corrected according to our guidelines.

Next time, we need to follow the rules and guidelines as accurately as possible.

**Pull request merged**
